development:
  dialect: postgres
  database: go_sample_web
  user: go
  password: gopher
  host: 127.0.0.1
  pool: 1

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/go_sample_web"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/go_sample_web"}}

